### ISSUE TITLE
Problema con la práctica NextJs

### ISSUE THREAD

**Issue by Gia-ui** [ULL-ESIT-DMSI-2223/nextjs-gianmarco-corbo-alu0101134741#1]
@crguezl Buenos días.
En la práctica ya he creado las dos rutas /pet y /image, donde en /pet está el generador de nombres mientras que en /image he implementado la obtención de una imagen de OpenAi y el mostrarla. El primero funciona sin problemas, pero con el segundo recibo un error 500 que no he conseguido solucionar de ninguna manera.
![error_generate_image](https://user-images.githubusercontent.com/72807522/210219972-904a8b7e-d968-404a-b31f-652e23d2c0fc.png)

Al comienzo pensé que podía ser un problema con la clave para poder acceder a OpenAi, pero como el servicio de generador de nombres funciona sin problemas entonces tiene que ser algo diferente, así que no consigo encontrar el error en el código.

El código de la api es el siguiente:
![codigo_api_generate_image](https://user-images.githubusercontent.com/72807522/210220576-c416837f-23b8-4ff5-aa1b-bb1e9157c295.png)

Mientras que el de image.js es:

![codigo_imagejs1](https://user-images.githubusercontent.com/72807522/210220617-00dd0735-73a5-4c18-9176-3650a9eed9a2.png)
![codigo_imagejs2](https://user-images.githubusercontent.com/72807522/210220623-62bca16f-24d1-4132-bba1-4ab4aeed147f.png)

La página está desplegada en el siguiente enlace de Netlify: https://astounding-rolypoly-a8f3d5.netlify.app/

**Comment by crguezl** [comment]
@Gia-ui 


Buen trabajo, vas por el buen camino 👍 


Varias cosas en estos ficheros:

```
✗ git -P diff --name-only
.env
package-lock.json
package.json
pages/api/generateImage.js
pages/image.js
```

1. Usa la versión 3.1 de openai:

  ```diff
  ✗ git -P diff package.json
  diff --git a/package.json b/package.json
  index a3cfdb8..a063be0 100644
  --- a/package.json
  +++ b/package.json
  @@ -9,7 +9,7 @@
     },
     "dependencies": {
       "next": "^12.1.6",
  -    "openai": "^3.0.0",
  +    "openai": "^3.1.0",
       "react": "17.0.2",
       "react-dom": "17.0.2"
     }
```
2.  En el server te falta responder así que se queda colgado. Ademas faltaba la declaración de `image_url`:

  ```diff
  ➜  nextjs-gianmarco-corbo-alu0101134741 git:(main) ✗ git -P diff pages/api/generateImage.js
  diff --git a/pages/api/generateImage.js b/pages/api/generateImage.js
  index 06eb21e..22c780c 100644
  --- a/pages/api/generateImage.js
  +++ b/pages/api/generateImage.js
  @@ -6,11 +6,16 @@ const configuration = new Configuration({
   const openai = new OpenAIApi(configuration);
   
   export default async function (req, res) {
  +  console.log(req.body);
  +
     const response = await openai.createImage({
         prompt: req.body.prompt,
         n: 1,
         size: req.body.size,
       });
  -    image_url = response.data.data[0].url;
  +  
  +
  +  const image_url = response.data.data[0].url;
  +  res.status(200).json({ result: image_url });
   }
  ```
3. El inglés en el placeholder esta un poco mal. Creo que quieres decir algo así: *"Paint  Bears in a Starry Night using Vincent van Gogh style*
4. Tuve que cambiar mi `API_KEY`

Con todo ello funciona:

<img width="517" alt="Captura de pantalla 2023-01-02 a las 12 08 32" src="https://user-images.githubusercontent.com/1142554/210230325-dd76d32f-fbfb-4867-8d03-df50f334c204.png">

**Comment by Gia-ui** [comment]
@crguezl  Vale, muschisimas gracias, he aplicado esos cambios y ya funciona
